# using ~/.pgpass to store user/password
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: zenappointments_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: zenappointments_test
  pool: 5
  timeout: 5000

production_asset_builder:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: zenappointments_prod
  pool: 5
  timeout: 5000

production:
  adapter: postgres
  encoding: utf8
  host: ec2-107-20-224-218.compute-1.amazonaws.com
  database: d6udff0armjpo
  user: khstfcobhbtapo
  password: 'ybDu_v31kVQDcBYhf86PkJA_0P'
  pool: 5
  timeout: 5000
